name: "Scenario: SDK Update"

on:
  push:
    paths:
      - "scenarios/sdk-update/**"
      - ".github/workflows/sdk-update.yml"
      - ".github/actions/setup-dotnetup/**"
  pull_request:
    paths:
      - "scenarios/sdk-update/**"
      - ".github/workflows/sdk-update.yml"
      - ".github/actions/setup-dotnetup/**"
  workflow_dispatch:

defaults:
  run:
    working-directory: scenarios/sdk-update


env:
  LOCAL_INSTALL_ROOT: .dotnet

jobs:
  build:
    name: Show updates for installed tooling
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup dotnetup
        uses: ./.github/actions/setup-dotnetup
        with:
          dotnet-install-root: ${{ env.LOCAL_INSTALL_ROOT }}
          dotnetup-manifest-path: .dotnetup.json
          working-directory: ${{ github.workspace }}/scenarios/sdk-update

      - name: Show dotnetup install state
        shell: bash
        run: |
          dotnetup list --manifest-path .dotnetup.json --install-path ${{ env.LOCAL_INSTALL_ROOT }}

      - name: Show updates for updates
        shell: bash
        run: |
          dotnetup update --manifest-path .dotnetup.json --install-path ${{ env.LOCAL_INSTALL_ROOT }}

      - name: Show dotnetup install state after update
        shell: bash
        run: |
          dotnetup list --manifest-path .dotnetup.json --install-path ${{ env.LOCAL_INSTALL_ROOT }}